Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.3

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Max: 110

Style/ClassAndModuleChildren:
  Enabled: false
